# Aby włączyć jedną z porządanych funkcji należy wpisać:
# make ...
# w miejsce kropek wpisujemy jedną z poniższych komend


double_chart:
	python NUM1.py double chart

double_miscalculation:
	python NUM1.py double miscalculation

float_chart:
	python NUM1.py float chart

float_miscalculation:
	python NUM1.py float miscalculation
